artifacts_roots: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
   root_dir: artifacts/data_validation
   unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
   STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
   root_dir: artifacts/data_transformation   
   data_path: artifacts/data_ingestion/winequality-red.csv


data_trainer:
   root_dir: artifacts/data_trainer
   train_path: artifacts/data_transformation/train.csv
   test_path: artifacts/data_transformation/test.csv
   model_name: model.joblib

model_evaluation:
   root_dir: artifacts/model_evaluation
   test_data_path: artifacts/data_transformation/test.csv
   model_path: artifacts/data_trainer/model.joblib
   metric_file_path: artifacts/model_evaluation/metrics.json
   mlflow_uri: 'https://dagshub.com/researchanalystforapurpose/FACIAL_BIOMETRIC_ATTENDENCE_SYSTEM.mlflow'
   # mlflow_uri: 'http://127.0.0.1:5000'

